apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tyk-dev
  labels:
    app: tyk-dev
  name: tyk-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyk-dev
  template:
    metadata:
      labels:
        app: tyk-dev
    spec:
      hostNetwork: true
      containers:
      - image: say2imran/tyk-image:1.0.0
        name: tyk-image
        volumeMounts:
          - name: kube-config
            mountPath: /app/kubeconfig/
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 8081
        imagePullPolicy: Always
        env:
          - name: KUBECONFIG
            value: "/app/kubeconfig/client.config"
          - name: PORT
            value: "8081"
      volumes:
        - name: kube-config
          hostPath:
            path: /var/snap/microk8s/current/credentials/
status: {}
