apiVersion: v1
kind: Service
metadata:
  namespace: tyk-dev
  name: tyk-dev
  labels:
    app: tyk-dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: tyk-dev
