apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.appName }}-{{ .Values.env }}
  labels:
    app: {{ .Values.appName }}-{{ .Values.env }}
  name: {{ .Values.appName }}-{{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-{{ .Values.env }}
    spec:
      containers:
      - image: {{ .Values.dockerRepo}}/{{ .Values.imageName }}:{{ .Values.imageVersion }}
        name: {{ .Values.appName }}-{{ .Values.env }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
status: {}
