apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.env }}
  labels:
    run: {{ .Values.appName }}-{{ .Values.env }}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: {{ .Values.appName }}-{{ .Values.env }}
