name: Build my Tyk image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Tyk Image
        run: docker build . -t tyk-image:v1.0.0