name: Build my Tyk image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code and Build Tyk Image
        uses: actions/checkout@4
        run: docker build . -t tyk-image:v1.0.0